apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata: 
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx  