apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: nginx
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    resources: {}
    volumeMounts: 
    - name: local-persistent-storage
      mountPath: /var/www/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: local-persistent-storage
    persistentVolumeClaim: 
      claimName: local-pvc
status: {}
